### Description ###
# Title: Makefile
# Author: Tyler Reed
# Auto-Compiles the Executable with the proper Arguments

# Compile Specification
Project3: Main.cpp
	g++ ./Main.cpp ./Server/Server.cpp ./Client/Client.cpp -pthread -o Project3

# Clean Specification
clean:
	rm -rf *.o Project3
