### Description ###
# Title: Makefile
# Author: Tyler Reed
# Auto-Compiles the Executable with the proper Arguments

# Compile Specification
Project2: Main.cpp
	g++ ./Main.cpp -pthread -x c++ -o Project2

# Clean Specification
clean:
	rm -rf *.o Project2
