### Description ###
# Title: Makefile
# Authors: Brain Quackenbush, Tyler Reed, Ashley Tharp
# Makefile for Operating Systems - Project 1 - Fall 2013

project1: main.cpp CPU.h CPU.cpp Memory.h Memory.cpp
	g++ ./main.cpp ./Memory.cpp ./CPU.cpp -o ./Simulation

clean:
	rm -rf *.o Simulation

